mysql:
  image: mysql:8.0
  storage: 5Gi
  rootPassword: root
  database: hospital

backend:
  image: rachapudi30570/hospital-backend1:v1
  replicas: 2
  port: 8080
  nodePort: 30083

frontend:
  image: rachapudi30570/hospital-frontend1:v1
  replicas: 2
  port: 8080
  nodePort: 30082

ingress:
  enabled: true
  host: hospital.local

autoscaling:
  backend:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60

  frontend:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
